spring.datasource.url=jdbc:mysql://localhost:3306/stationary
spring.datasource.username=Akhila
spring.datasource.password=Akhila@0820

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Akhilareeta143@gmail.com
spring.mail.password=ymlb azav exmd xcbm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000